### ISSUE TITLE
Handling of http URLs in Harmony Index.ref.xml does not work

### ISSUE THREAD

**Issue by bholl** [glencoesoftware/bioformats#3]
When using the bioformats plugin in ImageJ it would be great if it worked with Index.ref.xml files (Harmony datasets). Index.ref.xml contain an http URL pointing to a Harmony webservice where images can be downloaded. When using the bioformats plugin for opening such an Index.ref.xml file, the following error is thrown:
java.io.FileNotFoundException: C:\data\oris-karin\Oris-Pro_100914__2010-09-14T17_11_35-Measurement1\Images\http:\localhost\imagel.tiff (The filename, directory name, or volume label syntax is incorrect)
    at java.io.RandomAccessFile.open0(Native Method)
    at java.io.RandomAccessFile.open(Unknown Source)
    at java.io.RandomAccessFile.<init>(Unknown Source)
    at loci.common.NIOFileHandle.<init>(NIOFileHandle.java:123)
    at loci.common.Location.getHandle(Location.java:320)
    at loci.common.RandomAccessInputStream.<init>(RandomAccessInputStream.java:131)
    at loci.formats.in.HarmonyReader.initFile(HarmonyReader.java:396)
    at loci.formats.FormatReader.setId(FormatReader.java:1426)
    at loci.plugins.in.ImportProcess.initializeFile(ImportProcess.java:505)
    at loci.plugins.in.ImportProcess.execute(ImportProcess.java:143)
    at loci.plugins.in.Importer.showDialogs(Importer.java:140)
    at loci.plugins.in.Importer.run(Importer.java:76)
    at loci.plugins.LociImporter.run(LociImporter.java:78)
    at ij.IJ.runUserPlugIn(IJ.java:216)
    at ij.IJ.runPlugIn(IJ.java:180)
    at ij.Executer.runCommand(Executer.java:137)
    at ij.Executer.run(Executer.java:66)
    at java.lang.Thread.run(Unknown Source)

I'm attaching a prepared example with two images reference in an Index.ref.xml. In order to reproduce the issue, you'd need to setup a webserver serving http://localhost/image1.tiff and http://localhost/image2.tiff (or you modify the URLs in the Index.ref.xml file to point to a server where you'd put the image1.tiff and image2.tiff file).
[Oris-Pro_100914__2010-09-14T17_11_35-Measurement1.zip](https://github.com/glencoesoftware/bioformats/files/495940/Oris-Pro_100914__2010-09-14T17_11_35-Measurement1.zip)

**Comment by melissalinkert** [comment]
I can reproduce this problem; there are three separate issues:
1. the first referenced TIFF file has the relative name `imagel.tiff`, not `image1.tiff`; this is easy enough for us to fix in testing by modifying `Index.ref.xml` or renaming the TIFF file, but is just something to be aware of.
2. https://github.com/glencoesoftware/bioformats/blob/dev_5_1/components/formats-gpl/src/loci/formats/in/HarmonyReader.java#L652 needs to be updated to check if the filename is a URL (begins with `http`), so that the base directory is not always prepended to the TIFF path.
3. there is a small bug in https://github.com/glencoesoftware/bioformats/blob/dev_5_1/components/formats-common/src/loci/common/URLHandle.java which prevents backwards seeking when the TIFF files are read from a URL.

A fix for (2) is working locally; (3) is still in progress.  I expect to have a pull request open for both shortly.

**Comment by melissalinkert** [comment]
Corresponding fixes are now in https://github.com/glencoesoftware/bioformats/pull/4.

**Comment by bholl** [comment]
Great, thanks for the fix. I've tested it briefly and it works! We're testing with more datasets soon but for now the ticket can be closed.
